[aws]
symbol = "  "

[c]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[kotlin]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = false
threshold = 40
style = 'bold dimmed yellow'

[nodejs]
symbol = " "

[os.symbols]
Ubuntu = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[zig]
symbol = " "

[sudo]
symbol = "SU 🧙 "
style = 'bold italic red'
disabled = false

[character]
success_symbol = '[➜](bold green)' 
error_symbol = '[➜](bold red)'
